"use server";

import { revalidatePath } from "next/cache";
import { eq, inArray, sql } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db/client";
import { orderItems, orders, products } from "@/db/schema";
import { centsFromNumeric, numericFromCents } from "@/lib/money";
import { paymentMethods, pickupLocations } from "@/content/ordering";

/**
 * Checkout.
 *
 * @implements SHOP-9 — cash is refused for anything being shipped.
 * @implements SHOP-13 — a valid request produces an order and its summary.
 *
 * A Server Action is a public POST endpoint. Next's own docs are explicit:
 *
 *   "Server Functions are reachable via direct POST requests, not just through
 *    your application's UI. Always verify authentication and authorization
 *    inside every Server Function."
 *
 * So nothing here trusts the browser. The client sends slugs, quantities and
 * contact details; every price, every line total and the subtotal are read from
 * the database and computed here. There is deliberately no price field in the
 * input schema — an order cannot claim a price it was not charged, because
 * there is nowhere to put one (docs/backend.md §3).
 */

const PAYMENT_IDS = paymentMethods.map((method) => method.id) as [
  "zelle",
  "venmo",
  "cash",
];

const CheckoutInput = z.object({
  /**
   * One per checkout attempt, generated by the browser. Unique-constrained, so
   * a double-click or a retry on a flaky connection returns the first order
   * rather than creating a second (docs/backend.md §3).
   */
  idempotencyKey: z.uuid(),

  items: z
    .array(
      z.object({
        slug: z.string().min(1).max(200),
        quantity: z.number().int().min(1).max(999),
      }),
    )
    .min(1, "Your cart is empty.")
    .max(50),

  buyer: z.object({
    firstName: z.string().trim().min(1).max(100),
    lastName: z.string().trim().min(1).max(100),
    email: z.email().max(320),
  }),

  fulfilment: z.enum(["shipping", "pickup"]),
  shippingAddress: z.string().trim().max(500).optional(),
  pickupLocation: z.string().trim().max(300).optional(),

  paymentMethod: z.enum(PAYMENT_IDS),
});

export type CheckoutInput = z.infer<typeof CheckoutInput>;

export type OrderLine = {
  slug: string;
  name: string;
  quantity: number;
  unitPriceCents: number;
  lineTotalCents: number;
};

export type CheckoutResult =
  | {
      ok: true;
      /** Every number here is the server's, not the browser's. */
      order: {
        id: string;
        lines: OrderLine[];
        subtotalCents: number;
        totalCents: number;
        fulfilment: "shipping" | "pickup";
        paymentMethod: string;
        replayed: boolean;
      };
    }
  | { ok: false; error: string; fieldErrors?: Record<string, string> };

function failure(error: string, fieldErrors?: Record<string, string>): CheckoutResult {
  return { ok: false, error, fieldErrors };
}

export async function submitOrder(raw: unknown): Promise<CheckoutResult> {
  // 1. Parse. Anything malformed stops here, before a connection is opened.
  const parsed = CheckoutInput.safeParse(raw);
  if (!parsed.success) {
    const fieldErrors: Record<string, string> = {};
    for (const issue of parsed.error.issues) {
      const path = issue.path.join(".");
      if (path && !fieldErrors[path]) fieldErrors[path] = issue.message;
    }
    return failure("That order could not be read. Check the form and try again.", fieldErrors);
  }

  const input = parsed.data;

  // 2. Re-apply the fulfilment rules. The form already prevents all of this;
  //    that is UX. This is the enforcement, and it is the copy that matters
  //    when the request does not come from the form.
  if (input.paymentMethod === "cash" && input.fulfilment !== "pickup") {
    return failure("Cash is available for local pick-up only.", {
      paymentMethod: "Cash is available for local pick-up only.",
    });
  }

  if (input.fulfilment === "shipping" && !input.shippingAddress) {
    return failure("Enter the address to ship to.", {
      shippingAddress: "Enter the address to ship to.",
    });
  }

  if (input.fulfilment === "pickup") {
    if (!input.pickupLocation) {
      return failure("Choose a drop-off spot.", {
        pickupLocation: "Choose a drop-off spot.",
      });
    }
    // Must be one we actually offer, not an arbitrary string.
    if (!pickupLocations.includes(input.pickupLocation)) {
      return failure("That drop-off spot is not one we offer.", {
        pickupLocation: "Choose a drop-off spot from the list.",
      });
    }
  }

  // Duplicate slugs would let the same item be locked twice and priced
  // inconsistently; collapse them into one line.
  const quantities = new Map<string, number>();
  for (const item of input.items) {
    quantities.set(item.slug, (quantities.get(item.slug) ?? 0) + item.quantity);
  }

  const db = getDb();

  // 3. Idempotency, checked before doing any work.
  const existing = await findByIdempotencyKey(input.idempotencyKey);
  if (existing) return existing;

  try {
    const result = await db.transaction(async (tx) => {
      // 4. Re-read price and stock under a row lock. Without FOR UPDATE two
      //    concurrent checkouts can both read "1 in stock" and both succeed.
      const rows = await tx
        .select({
          id: products.id,
          slug: products.slug,
          name: products.name,
          basePrice: products.basePrice,
          stockQuantity: products.stockQuantity,
        })
        .from(products)
        .where(inArray(products.slug, [...quantities.keys()]))
        .for("update");

      const found = new Map(rows.map((row) => [row.slug, row]));

      for (const [slug, quantity] of quantities) {
        const product = found.get(slug);
        if (!product) {
          throw new CheckoutError(
            "Something in your cart is no longer available. Please review it and try again.",
          );
        }
        if (product.stockQuantity < quantity) {
          throw new CheckoutError(
            `${product.name} only has ${product.stockQuantity} left. Please adjust your cart.`,
          );
        }
      }

      // 5. Compute the money. This is the only place a total is produced.
      const lines: OrderLine[] = [];
      for (const [slug, quantity] of quantities) {
        const product = found.get(slug)!;
        const unitPriceCents = centsFromNumeric(product.basePrice);
        lines.push({
          slug,
          name: product.name,
          quantity,
          unitPriceCents,
          lineTotalCents: unitPriceCents * quantity,
        });
      }

      const subtotalCents = lines.reduce(
        (total, line) => total + line.lineTotalCents,
        0,
      );
      // Shipping is not modelled yet, so the total is the subtotal. Kept as a
      // separate column and a separate variable so adding it later does not
      // mean discovering that "subtotal" meant "total" all along.
      const shippingCents = 0;
      const totalCents = subtotalCents + shippingCents;

      // 6. Write.
      const [order] = await tx
        .insert(orders)
        .values({
          orderType: "shop",
          idempotencyKey: input.idempotencyKey,
          firstName: input.buyer.firstName,
          lastName: input.buyer.lastName,
          customerEmail: input.buyer.email,
          paymentMethod: input.paymentMethod,
          fulfilmentType: input.fulfilment,
          shippingAddress:
            input.fulfilment === "shipping" ? input.shippingAddress : null,
          dropoffLocationName:
            input.fulfilment === "pickup" ? input.pickupLocation : null,
          subtotal: numericFromCents(subtotalCents),
          shippingCost: numericFromCents(shippingCents),
          totalPrice: numericFromCents(totalCents),
        })
        .returning({ id: orders.id });

      await tx.insert(orderItems).values(
        lines.map((line) => ({
          orderId: order.id,
          productId: found.get(line.slug)!.id,
          productName: line.name,
          unitPrice: numericFromCents(line.unitPriceCents),
          quantity: line.quantity,
        })),
      );

      /**
       * Stock is held the moment a request is placed, not when payment clears.
       * Without this the FOR UPDATE above would be pointless — the lock exists
       * precisely so the decrement is safe.
       *
       * requirements/shop_requirements.md listed this as an open item; it is
       * now decided. The consequence to plan for: an abandoned request holds
       * stock until an admin cancels it, and releasing stock on cancellation is
       * not built.
       */
      for (const line of lines) {
        await tx
          .update(products)
          .set({
            stockQuantity: sql`${products.stockQuantity} - ${line.quantity}`,
          })
          .where(eq(products.id, found.get(line.slug)!.id));
      }

      return {
        ok: true as const,
        order: {
          id: order.id,
          lines,
          subtotalCents,
          totalCents,
          fulfilment: input.fulfilment,
          paymentMethod: input.paymentMethod,
          replayed: false,
        },
      };
    });

    /**
     * Stock changed, so the grid and item pages are stale for anyone navigating
     * client-side.
     *
     * Isolated deliberately. The transaction has committed by this point, so a
     * failure here — no request context, a cache backend hiccup — must not be
     * reported as a failed order. Letting it reach the catch below would tell
     * the customer their order did not go through while it sits in the
     * database, and invite a retry for an order that already exists.
     */
    try {
      revalidatePath("/shop");
    } catch (error) {
      console.error("order committed, but revalidation failed", error);
    }

    return result;
  } catch (error) {
    if (error instanceof CheckoutError) return failure(error.message);

    // A concurrent request with the same key can lose the race between the
    // check above and the insert; the unique constraint catches it, and the
    // winner's order is the answer.
    if (isUniqueViolation(error)) {
      const replayed = await findByIdempotencyKey(input.idempotencyKey);
      if (replayed) return replayed;
    }

    console.error("checkout failed", error);
    return failure("Something went wrong saving your order. Please try again.");
  }
}

class CheckoutError extends Error {}

function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: unknown }).code === "23505"
  );
}

/**
 * Returns the already-recorded order for a key, if there is one.
 *
 * A replay must return the *original* numbers, not recompute them — prices may
 * have changed since, and the customer agreed to what they were shown.
 */
async function findByIdempotencyKey(
  key: string,
): Promise<CheckoutResult | undefined> {
  const db = getDb();

  const [order] = await db
    .select()
    .from(orders)
    .where(eq(orders.idempotencyKey, key))
    .limit(1);

  if (!order) return undefined;

  const items = await db
    .select()
    .from(orderItems)
    .where(eq(orderItems.orderId, order.id));

  return {
    ok: true,
    order: {
      id: order.id,
      lines: items.map((item) => {
        const unitPriceCents = centsFromNumeric(item.unitPrice);
        return {
          slug: "",
          name: item.productName,
          quantity: item.quantity,
          unitPriceCents,
          lineTotalCents: unitPriceCents * item.quantity,
        };
      }),
      subtotalCents: centsFromNumeric(order.subtotal),
      totalCents: centsFromNumeric(order.totalPrice),
      fulfilment: order.fulfilmentType as "shipping" | "pickup",
      paymentMethod: order.paymentMethod ?? "",
      replayed: true,
    },
  };
}
